name: Data validity tests

on: [push, pull_request]

jobs:

  test:
    name: QA checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install dependencies
      run: pip install -q pandas~=1.1.4
    - name: test CSV files
      run: |
        python3 script/test_csv.py
        python3 script/test_join.py
    - name: test JSON files
      # quick trick for running job while debugging scripts...
      if: ${{ always() }}
      run: python3 script/test_json.py
