name: Data validity tests

on: [push, pull_request]

jobs:

  test:
    name: Test invariants in dati-regioni/*.csv
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install dependencies
      run: pip install -q pandas~=1.1.4
    - name: run test script
      run: python3 script/test_csv.py
